name: Test, Build, and Push Image to Docker Efficient Version

on:
  push:
    branches:
      - 'master'
      - 'development'
    tags:
      - 'v*'

env:
  DOCKER_REPO_NAME: mde9304/mywebclass

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/*"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache
            ./node_modules
          key: ${{ runner.os }}-${{ env.DOCKER_REPO_NAME }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.DOCKER_REPO_NAME }}-
            ${{ runner.os }}-

      - name: Install and test Playwright
        run: |
          npm install
          npx playwright install
          npx playwright test --config=playwright.config.js

      - name: Login to DockerHub
        if: ${{ needs.build.outputs.tests-passed == 'success' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        if: ${{ needs.build.outputs.tests-passed == 'success' }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_REPO_NAME }}

      - name: Set up QEMU and Docker Buildx
        if: ${{ needs.build.outputs.tests-passed == 'success' }}
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        if: ${{ needs.build.outputs.tests-passed == 'success' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: 'linux/arm64/v8, linux/amd64'
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
